# Twilio configuration
TWILIO_ACCOUNT_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_PHONE_NUMBER = ""
TWILIO_MESSAGE_SERVICE_SID = ""

# Typeform configuration
TYPEFORM_AUTH = "Bearer "
TYPEFORM_SIGNUP_FORM_ID = ""
TYPEFORM_SCHOLARSHIP_FORM_ID = ""
TITLE_FIELD_ID = ""
URL_FIELD_ID = ""
AMOUNT_FIELD_ID = ""
DEADLINE_FIELD_ID = ""
ELIGIBILITY_FIELD_ID = ""

# Files
USERS_FILE = "users.json"
SCHOLARSHIPS_FILE = "scholarships.json"

# Versioning
API_VERSION = "1.0.0"
SMS_VERSION = "1.0.0"
SCHOLARSHIPS_VERSION = "1.0.0"

# API Authentication
API_AUTHENTICATION = "Basic NTY5MmVhOWItNzBkYy00M2YxLTllMzEtOGE0ZGI5M2ZiZWUy"
